synctl

Show the no. linked tests when use synctl get location
[Kanban Card](https://instana.kanbanize.com/ctrl_board/132/cards/127323/details/)

show no. of linked tests

---

README.md
synctl

- Add patch operation
- Add patch mark synthetic call
- Add patch scriptFile
[Kanban Card](https://instana.kanbanize.com/ctrl_board/132/cards/127323/details/)

Add patch options

---

README.md
synctl

Show location details
[Kanban Card](https://instana.kanbanize.com/ctrl_board/132/cards/132499/details/)

Show location details

---

README.md
synctl

set timeout when create test
[Kanban Card](https://instana.kanbanize.com/ctrl_board/132/cards/132700/details/)

set timeout when create test

---

synctl

Fix an issue when test is none.

fix test is none

---

README.md
synctl

support browser test type WebpageAction
- [Story](https://instana.kanbanize.com/ctrl_board/132/cards/132702/details/)

support browser test type WebpageAction

---

README.md
synctl

enhance README and command help message.

update helper message and readme

---

synctl

modify result when synctl create test

modify result when synctl create test

---

synctl

Display pop version when get location list
[Kanban Card](https://instana.kanbanize.com/ctrl_board/132/cards/136949/details/)

display pop version

---

synctl

synctl get test turn very slow when test > 5000.
Disable success rate and latency
[Kanban Card](https://instana.kanbanize.com/ctrl_board/132/cards/136033/details/)

disable success rate and latency

---

synctl

Fix record video issue for browser tests.

fix record video

---

README.md
synctl

Enhance update command
[Kanban Card](https://instana.kanbanize.com/ctrl_board/132/cards/132500/details/)

enhancement on update command

---

README.md
synctl

Update syntheticType label 
[Kanban Card](https://instana.kanbanize.com/ctrl_board/132/cards/142760/details/)

Modify synthetic type

---

README.md
synctl

support patching the customProperties of test payload 
[Kanban Card](https://instana.kanbanize.com/ctrl_board/132/cards/141373/details/)

add patch custom properties

---

README.md
synctl

CRUD for smart alerts
[Kanban Card](https://instana.kanbanize.com/ctrl_board/132/cards/133967/details/)

CRUD for smart alerts

---

README.md
synctl

patch multiple custom-properties
[Kanban Card](https://instana.kanbanize.com/ctrl_board/132/cards/143713/details/)

patch multiple custom-properties

---

README.md
synctl

support mutilple options when update test
[Kanban card](https://instana.kanbanize.com/ctrl_board/132/cards/143397/details/)

support multiple options when update test

---

README.md
synctl

support multiple options when update alert
[Kanban Card](https://instana.kanbanize.com/ctrl_board/132/cards/143397/details/)

update alert with multiple options

---

README.md
synctl

support tagFilterExpression when synctl create/update alert
[Kanban card](https://instana.kanbanize.com/ctrl_board/132/cards/145754/details/)

enhance create/update alert

---

README.md
synctl

1. synctl exit normally with 0, and 1(failure)
2. use exit_synctl.

replace exit with exit_synctl

---

README.md
synctl

some enhancements 
[Kanban card](https://instana.kanbanize.com/ctrl_board/132/cards/145985/details/)

Enhancements

---

synctl/cli.py

When get location, synctl throws an error. 
[Kanban Card](https://instana.kanbanize.com/ctrl_board/132/cards/147395/details/)

get location error fix

---

README.md
synctl/cli.py

not show latency and success rate by default
[Knaban Card](https://instana.kanbanize.com/ctrl_board/132/cards/147404/details/)

Show result fix

---

synctl/cli.py

show total no. of credentials when synctl get red
[Knaban Card](https://instana.kanbanize.com/ctrl_board/132/cards/147406/details/)

show total no. of credentials

---

synctl/cli.py

Show location type when synctl get location
[Kanban card](https://instana.kanbanize.com/ctrl_board/132/cards/147408/details/)

show location type

---

synctl/cli.py

Show error message when exiting synctl  (`KeyboardInterrupt`)

Exit error

---

README.md
synctl/cli.py

patch test browser type
[Kanban card](https://instana.kanbanize.com/ctrl_board/132/cards/147922/details/)

add patch browser type

---

README.md

Synthetic CLI command documentation: fix wrong examples
[Kanban card](https://instana.kanbanize.com/ctrl_board/132/cards/149258/details/)

Fix wrong examples

---

README.md
synctl/cli.py

- Ask for token when --token is not used
- Show encrypted token when `synctl config list --show-token`
- [Story](https://instana.kanbanize.com/ctrl_board/132/cards/150959/details/)

Hide token

---

README.md
synctl/cli.py

Add update a credential
[Story](https://instana.kanbanize.com/ctrl_board/132/cards/150984/details/)

add update cred

---

README.md
synctl/cli.py

- save results to files based on their result id
- output logs
- add option window-size
[Story](https://instana.kanbanize.com/ctrl_board/132/cards/158337/details/)

Enhance test results

---

README.md
synctl/cli.py

Enhance helper message and readme

Enhance pop size

---

synctl/cli.py

fix duplicate error

---

synctl/cli.py

fix indentation

---

synctl/cli.py

Fix some variables which is built in type, and enhancement.

enhance set frequency

---

README.md
docs/synctl-create-test.md
docs/synctl-patch-test.md
docs/synctl-update-test.md
synctl/cli.py

Enhancements for SSL tests
[Story](https://jsw.ibm.com/browse/INSTA-5073)

enhance ssl test

---

synctl/cli.py

missing option - `--validation-string` in create command

fix validation string

---

docs/synctl-create-alert.md
synctl/cli.py

refer - [issue](https://github.com/instana/synthetic-synctl/issues/91)
Create alert with json payload
[Story](https://jsw.ibm.com/secure/RapidBoard.jspa?rapidView=59855&projectKey=INSTA&view=detail&selectedIssue=INSTA-9559&quickFilter=223459#)

create alert with json payload

---

README.md
docs/synctl-create-test.md
docs/synctl-patch-test.md
docs/synctl-update-test.md
synctl/cli.py

See discussion on https://instana.slack.com/archives/C07B7HC47DX/p1720003861324619
refactor --from-file option
[Jira issue](https://jsw.ibm.com/browse/INSTA-9946?)

Enhancement

---

README.md
docs/synctl-create-alert.md
docs/synctl-create-test.md
docs/synctl-credential.md
docs/synctl-delete-alert.md
docs/synctl-delete-loc.md
docs/synctl-delete-test.md
docs/synctl-get-alert.md
docs/synctl-get-app.md
docs/synctl-get-loc.md
docs/synctl-get-result.md
docs/synctl-get-test.md
docs/synctl-patch-test.md
docs/synctl-update-alert.md
docs/synctl-update-test.md

see [https://instana.slack.com/archives/C02AZCPACMQ/p1721204507681689](https://instana.slack.com/archives/C02AZCPACMQ/p1721204507681689)

enhance docs

---

synctl/cli.py

fix cred is empty

---

docs/synctl-create-test.md
docs/synctl-get-app.md
docs/synctl-update-test.md
synctl/cli.py

Associate synthetic test with multiple applications, websistes and mobileApplications
[Story ](https://jsw.ibm.com/browse/INSTA-8623)

 INSTA-8623 add websites and mobile monitoring

---

synctl/cli.py

- Create credential with associated applications, websites and mobile applications
- Patch the associations of a Synthetic Credential
- Retrieve credential details
[Story](https://jsw.ibm.com/browse/INSTA-8327)

INSTA-8327 new server apis

---

docs/synctl-get-datacenter.md
synctl/cli.py

Update synctl for new server APIs related to Synthetic datacenters
- `synctl get datacenter`
- `synctl get datacenter <datacenter-id> --show-details`
- `synctl get datacenter <datacenter-id> --show-json`
[Story](https://jsw.ibm.com/browse/INSTA-16270)

INSTA-16270 Update synctl for new server APIs related to Synthetic datacenters

---

docs/synctl-create-alert.md
docs/synctl-update-alert.md
synctl/cli.py

Customer reported an issue. 
See [slack conversation](https://instana.slack.com/archives/C08LD1Y0VEX/p1743764475370259)
Add new fields for the smart alerts:
- --custom-payloads 
- --grace-period 
[Jira card](https://jsw.ibm.com/browse/INSTA-32963)

INSTA-32963: Enhance smart alert 

---

docs/synctl-create-test.md
docs/synctl-get-test.md
docs/synctl-patch-test.md
docs/synctl-update-test.md
synctl/cli.py

Add support for DNS test type.
[Kanban Card](https://jsw.ibm.com/browse/INSTA-23211)

INSTA-23211:  Update synctl to include DNS test type

---

docs/synctl-get-result.md
docs/synctl-get-test.md
docs/synctl-run-test.md
synctl/cli.py

Support run now tests
- Run a CI-CD test
```
synctl run test "$TEST-ID" --location "$LOCATION-ID"
```
- Lists all CI-CD tests 
```
synctl get test --CI-CD
```
- Show a CI-CD test result by a given test result id
```
synctl get test --result  "$RESULT-ID" --CI-CD
```
[Jira Card](https://jsw.ibm.com/browse/INSTA-13215)

INSTA-13215: Support run now

---

docs/synctl-get-loc.md
synctl/cli.py

- Add a notice for "get pop-size" command
- Add --show-json support for get location command
- [Story 1](https://jsw.ibm.com/browse/INSTA-48366)
- [Story 2](https://jsw.ibm.com/browse/INSTA-10008)

INSTA-48366, INSTA-10008: Synctl enhancement

---

docs/synctl-create-alert.md
docs/synctl-update-alert.md
synctl/cli.py

Support multiple custom payloads for `synctl create/update alert` command
- [Slack Thread](https://instana.slack.com/archives/C08LD1Y0VEX/p1756211626903219)
- [Jira Card](https://jsw.ibm.com/browse/INSTA-51398)

Support multiple custompayloads
